[package]
name = "async_requests"
version = "0.1.0"
authors = ["steavot <tomsteavenson@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1.17"
reqwest = "0.9.11"
futures = "0.1.25"
serde = "1.0.89"
serde_derive = "1.0.89"
failure = "0.1.5"
log = "0.4.6"
env_logger = "0.6.1"
